version: '3'

services:
  db:
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=perservant
    expose:
      - '5432'
    image: 'postgres'
    # build: ./db/
    ports:
      - '5432:5432'
